project_id = "iueeeaoptvmxlxgcrmck"

[functions.manage-users]
verify_jwt = false

[functions.cleanup-attachments]
verify_jwt = false

[functions.api-v1]
verify_jwt = false

[functions.create-hermes-job]
verify_jwt = false

[functions.hermes-gateway]
verify_jwt = false


[functions.prepare-devis-followup]
verify_jwt = false
