// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iueeeaoptvmxlxgcrmck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1ZWVlYW9wdHZteGx4Z2NybWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3Njg1MTksImV4cCI6MjA4NzM0NDUxOX0.AYZaoUk8F7SRh-Jw8oJJboBpJP7QF2uWqoVCToqz0BM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});